2025-08-01 16:54:06,021 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 16:54:06,021 ERROR: \u274c Attempt 1 failed: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
2025-08-01 16:54:09,036 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 16:54:09,036 ERROR: \u274c Attempt 2 failed: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
2025-08-01 16:54:13,119 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 16:54:13,119 ERROR: \u274c Attempt 3 failed: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
2025-08-01 16:58:07,348 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 17:22:54,406 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 17:36:13,881 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 17:36:54,394 INFO: \u2705 Saved satellite image to data/pollution_2025-08-01.png
2025-08-01 17:52:25,895 INFO: \u2705 Saved image for 2025-07-01
2025-08-01 17:52:26,175 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-01: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-01&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022198606530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-08-01 17:52:27,196 INFO: \u2705 Saved image for 2025-07-08
2025-08-01 17:52:27,321 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-08: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-08&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022198606620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-08-01 17:52:28,625 INFO: \u2705 Saved image for 2025-07-15
2025-08-01 17:52:28,659 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-15: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-15&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221986065C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-08-01 17:52:34,773 INFO: \u2705 Saved image for 2025-07-01
2025-08-01 17:52:34,901 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-01: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-01&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001830DC06530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-08-01 17:52:36,411 INFO: \u2705 Saved image for 2025-07-08
2025-08-01 17:52:36,442 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-08: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-08&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001830DC06620>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2025-08-01 17:52:37,583 INFO: \u2705 Saved image for 2025-07-15
2025-08-01 17:52:37,634 WARNING: \u26a0\ufe0f API fetch failed for 2025-07-15: HTTPSConnectionPool(host='api.caeli.io', port=443): Max retries exceeded with url: /v1/no2?date=2025-07-15&bbox=36.65%2C-0.40%2C36.95%2C-0.10 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001830DC065C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
